description = 'Module providing the core classes and interfaces for telemetry metrics in SonarQube.'

sonar {
    properties {
        property 'sonar.projectName', "${projectTitle} :: Server :: Telemetry Core"
    }
}

dependencies {
    compileOnlyApi 'com.github.spotbugs:spotbugs-annotations'

    implementation project(':sonar-core')
    implementation project(':server:sonar-process')

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.sonarsource.sonarqube:sonar-events-api'

    testImplementation(platform("org.junit:junit-bom"))
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.sonarsource.sonarqube:sonar-events-server'
    testImplementation 'org.sonarsource.sonarqube:gessie-server-app'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.test {
    useJUnitPlatform()
}
