CREATE TABLE "RULE_DESC_SECTIONS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "RULE_UUID" CHARACTER VARYING(40) NOT NULL,
    "KEE" CHARACTER VARYING(50) NOT NULL,
    "CONTENT" CHARACTER LARGE OBJECT NOT NULL,
    "CONTEXT_KEY"  CHARACTER VARYING(40),
    "CONTEXT_DISPLAY_NAME"  CHARACTER VARYING(50)
);
ALTER TABLE "RULE_DESC_SECTIONS" ADD CONSTRAINT "PK_RULE_DESC_SECTIONS" PRIMARY KEY("UUID");
