CREATE TABLE "PORTFOLIOS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "KEE" CHARACTER VARYING(400) NOT NULL,
    "NAME" CHARACTER VARYING(2000) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(2000),
    "ROOT_UUID" CHARACTER VARYING(40) NOT NULL,
    "PARENT_UUID" CHARACTER VARYING(40),
    "PRIVATE" BOOLEAN NOT NULL,
    "SELECTION_MODE" CHARACTER VARYING(50) NOT NULL,
    "SELECTION_EXPRESSION" CHARACTER VARYING(4000),
    "CREATED_AT" BIGINT NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL,
    "BRANCH_KEY" CHARACTER VARYING(255),
    "MEASURES_MIGRATED" BOOLEAN NOT NULL DEFAULT FALSE
);
ALTER TABLE "PORTFOLIOS" ADD CONSTRAINT "PK_PORTFOLIOS" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "UNIQ_PORTFOLIOS_KEE" ON "PORTFOLIOS"("KEE" NULLS FIRST);
