CREATE TABLE "RULE_TAGS"(
    "RULE_UUID" CHARACTER VARYING(40) NOT NULL,
    "ORGANIZATION_UUID" CHARACTER VARYING(40),
    "IS_SYSTEM_TAG" BOOLEAN NOT NULL,
    "VALUE" CHARACTER VARYING(40) NOT NULL
);
