CREATE TABLE "RULE_IMPACT_CHANGES"(
    "NEW_SOFTWARE_QUALITY" CHARACTER VARYING(40) NOT NULL,
    "OLD_SOFTWARE_QUALITY" CHARACTER VARYING(40) NOT NULL,
    "NEW_SEVERITY" CHARACTER VARYING(40) NOT NULL,
    "OLD_SEVERITY" CHARACTER VARYING(40) NOT NULL,
    "RULE_CHANGE_UUID" CHARACTER VARYING(40) NOT NULL
);