CREATE TABLE "DEPRECATED_RULE_KEYS" (
  "UUID"  VARCHAR(40) NOT NULL,
  "RULE_ID" INTEGER NOT NULL,
  "OLD_REPOSITORY_KEY" VARCHAR(200) NOT NULL,
  "OLD_RULE_KEY" VARCHAR(255) NOT NULL,
  "CREATED_AT" BIGINT,

  CONSTRAINT "PK_DEPRECATED_RULE_KEYS" PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX "UNIQ_DEPRECATED_RULE_KEYS" ON "DEPRECATED_RULE_KEYS" ("OLD_REPOSITORY_KEY", "OLD_RULE_KEY");
CREATE UNIQUE INDEX "RULE_ID_DEPRECATED_RULE_KEYS" ON "DEPRECATED_RULE_KEYS" ("RULE_ID");
