CREATE TABLE "PERSONS" (
  "ID" INTEGER NOT NULL AUTO_INCREMENT (1,1),
  "LOGIN" VARCHAR(50),
  "AGE" INTEGER,
  "ENABLED" BOOLEAN,
  "UPDATED_AT" TIMESTAMP,
  "COEFF" DOUBLE,
  "PHONE_NUMBERS" VARCHAR(500)
);

CREATE TABLE "PHONE_NUMBERS" (
  "PERSON_ID" INTEGER NOT NULL,
  "PHONE_NUMBER" VARCHAR(100)
);
