CREATE TABLE "ES_QUEUE" (
  "UUID" VARCHAR(40) NOT NULL PRIMARY KEY,
  "DOC_TYPE" VARCHAR(40) NOT NULL,
  "DOC_UUID" VARCHAR(255) NOT NULL,
  "CREATED_AT" BIGINT NOT NULL
);
CREATE UNIQUE INDEX "PK_ES_QUEUE" ON "ES_QUEUE" ("UUID");
