CREATE TABLE "GROUP_ROLES"(
    "ID" INTEGER NOT NULL AUTO_INCREMENT (1,1),
    "ORGANIZATION_UUID" VARCHAR(40) NOT NULL,
     "COMPONENT_UUID" VARCHAR(50),
    "GROUP_ID" INTEGER,
    "RESOURCE_ID" INTEGER,
    "ROLE" VARCHAR(64) NOT NULL
);
ALTER TABLE "GROUP_ROLES" ADD CONSTRAINT "PK_GROUP_ROLES" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "UNIQ_GROUP_ROLES" ON "GROUP_ROLES"("ORGANIZATION_UUID", "GROUP_ID", "RESOURCE_ID", "ROLE");
CREATE UNIQUE INDEX "GROUP_ROLES_UNIQ" ON "GROUP_ROLES"("ORGANIZATION_UUID", "GROUP_ID", "COMPONENT_UUID", "ROLE");
CREATE INDEX "GROUP_ROLES_RESOURCE" ON "GROUP_ROLES"("RESOURCE_ID");
CREATE INDEX "GROUP_ROLES_COMPONENT_UUID" ON "GROUP_ROLES"("COMPONENT_UUID");
