/*
 * Sonar, open source software quality management tool.
 * Copyright (C) 2008-2012 SonarSource
 * mailto:contact AT sonarsource DOT com
 *
 * Sonar is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * Sonar is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Sonar; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02
 */
package org.sonar.plugins.findbugs;

import org.sonar.api.profiles.ProfileExporter;
import org.sonar.api.profiles.RulesProfile;
import org.sonar.api.resources.Java;
import org.sonar.api.rules.ActiveRule;
import org.sonar.api.utils.SonarException;
import org.sonar.plugins.findbugs.xml.Bug;
import org.sonar.plugins.findbugs.xml.ClassFilter;
import org.sonar.plugins.findbugs.xml.FindBugsFilter;
import org.sonar.plugins.findbugs.xml.Match;

import java.io.IOException;
import java.io.Writer;
import java.util.List;

public class FindbugsProfileExporter extends ProfileExporter {

  public FindbugsProfileExporter() {
    super(FindbugsConstants.REPOSITORY_KEY, FindbugsConstants.PLUGIN_NAME);

    setSupportedLanguages(Java.KEY);
    setMimeType("application/xml");
  }

  @Override
  public void exportProfile(RulesProfile profile, Writer writer) {
    List<ActiveRule> activeRulesByRepository = profile.getActiveRulesByRepository(FindbugsConstants.REPOSITORY_KEY);
    FindBugsFilter filter = buildFindbugsFilter(activeRulesByRepository);

    writeXml(filter, writer);
  }

  public void exportExclusions(String[] exclusions, Writer writer) {
    FindBugsFilter filter = new FindBugsFilter();
    if (exclusions != null) {
      for (String exclusion : exclusions) {
        ClassFilter classFilter = new ClassFilter(FindbugsAntConverter.antToJavaRegexpConvertor(exclusion));
        filter.addMatch(new Match(classFilter));
      }
    }

    writeXml(filter, writer);
  }

  private static void writeXml(FindBugsFilter filter, Writer writer) {
    try {
      writer.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
      writer.write("<!-- Generated by Sonar -->\n");
      writer.write(filter.toXml());
    } catch (IOException e) {
      throw new SonarException("Fail to export Findbugs configuration", e);
    }
  }

  protected static FindBugsFilter buildFindbugsFilter(List<ActiveRule> activeRules) {
    FindBugsFilter root = new FindBugsFilter();

    for (ActiveRule activeRule : activeRules) {
      if (FindbugsConstants.REPOSITORY_KEY.equals(activeRule.getRepositoryKey())) {
        Match child = new Match();
        child.setBug(new Bug(activeRule.getConfigKey()));
        root.addMatch(child);
      }
    }

    return root;
  }
}
