# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_files.add(['app/controllers/api/*.rb', 'INDEX'])
  
  rdoc.main = "INDEX" 
  rdoc.title = "Sonar API"
  rdoc.template = 'lib/sonar_rdoc_template'
  rdoc.rdoc_dir = 'doc' # rdoc output folder
  rdoc.options << '--inline-source' << '--charset=UTF-8'
end
