CREATE TABLE "ISSUES_IMPACTS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "ISSUE_KEY" CHARACTER VARYING(40) NOT NULL,
    "SOFTWARE_QUALITY" CHARACTER VARYING(40) NOT NULL,
    "SEVERITY" CHARACTER VARYING(40) NOT NULL
);
ALTER TABLE "ISSUES_IMPACTS" ADD CONSTRAINT "PK_ISSUES_IMPACTS" PRIMARY KEY("UUID");
CREATE INDEX "ISSUES_IMPACTS_ISSUE_KEY" ON "ISSUES_IMPACTS"("ISSUE_KEY" NULLS FIRST);
