compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.2.2.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-echo-execute.cjs
    spec: "https://yarnplugins.com/plugin-echo-execute"
