CREATE TABLE "NEW_CODE_REFERENCE_ISSUES"(
    "UUID" VARCHAR(40) NOT NULL,
    "ISSUE_KEY" VARCHAR(50) NOT NULL,
    "CREATED_AT" BIGINT NOT NULL
);
ALTER TABLE "NEW_CODE_REFERENCE_ISSUES" ADD CONSTRAINT "PK_NEW_CODE_REFERENCE_ISSUES" PRIMARY KEY("UUID");
