/*
 * SonarQube
 * Copyright (C) SonarSource Sàrl
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.db.version;

import java.util.Set;

public final class SonarQubeSchema {

  /**
   * List of all the tables.
   * This list is hardcoded because we didn't succeed in using java.sql.DatabaseMetaData#getTables() in the same way
   * for all the supported databases, particularly due to Oracle results.
   */
  public static final Set<String> TABLES = Set.of(
    "a3s_analysis_usages",
    "a3s_context_items",
    "a3s_contexts",
    "a3s_purge_tasks",
    "active_rules",
    "active_rule_parameters",
    "admin_alert_status",
    "agent_jobs",
    "agent_orch_tasks",
    "agent_sched_proc_issues",
    "agent_schedules",
    "alm_settings",
    "alm_pats",
    "analysis_properties",
    "anticipated_transitions",
    "app_branch_project_branch",
    "app_projects",
    "arch_boundaries",
    "arch_boundary_descriptors",
    "arch_directives",
    "arch_graph_blobs",
    "arch_graph_metadata",
    "arch_model_patterns",
    "arch_models",
    "arch_org_placeholders",
    "arch_org_sdks",
    "arch_patterns",
    "arch_proj_org_compo",
    "arch_proj_relations",
    "arch_scanner_data",
    "atlassian_auth_details",
    "audits",
    "cag_purge_tasks",
    "cag_usage",
    "ce_activity",
    "ce_queue",
    "ce_task_characteristics",
    "ce_task_input",
    "ce_task_message",
    "ce_scanner_context",
    "components",
    "dashboards",
    "default_qprofiles",
    "deprecated_rule_keys",
    "devops_perms_mapping",
    "dop_pr_snapshots",
    "duplications_index",
    "es_queue",
    "events",
    "event_component_changes",
    "external_groups",
    "file_sources",
    "finding_locations",
    "findings",
    "github_orgs_groups",
    "groups",
    "groups_users",
    "group_roles",
    "hunter_agent_jobs",
    "hunter_agent_runs",
    "hunter_scheduled_tasks",
    "integration_bindings",
    "integration_configs",
    "internal_component_props",
    "internal_properties",
    "issue_count_dimensions",
    "issue_count_history",
    "issue_stats_by_rule_key",
    "issue_ttr_history",
    "issues",
    "issues_fixed",
    "issues_impacts",
    "issue_changes",
    "jira_org_bindings",
    "jira_org_bindings_pending",
    "jira_project_bindings",
    "jira_selected_work_types",
    "jira_work_items",
    "jira_work_items_resources",
    "llm_providers",
    "llm_provider_mappings",
    "measure_history",
    "measure_key_mapping",
    "measures",
    "metrics",
    "migration_logs",
    "new_code_periods",
    "new_code_reference_issues",
    "notif_group_subscriptions",
    "notifications",
    "org_qprofiles",
    "organization_configs",
    "permission_templates",
    "perm_templates_users",
    "perm_templates_groups",
    "perm_tpl_characteristics",
    "plugins",
    "portfolios",
    "portfolio_projects",
    "portfolio_proj_branches",
    "portfolio_references",
    "projects",
    "project_alm_settings",
    "project_badge_token",
    "project_branches",
    "project_configs",
    "project_dependencies",
    "project_links",
    "project_measures",
    "project_qprofiles",
    "project_qgates",
    "properties",
    "push_events",
    "qprofile_changes",
    "qprofile_edit_groups",
    "qprofile_edit_users",
    "quality_gates",
    "qgate_user_permissions",
    "qgate_group_permissions",
    "quality_gate_conditions",
    "remediation_agent_jobs",
    "remediation_sched_tasks",
    "saml_message_ids",
    "report_schedules",
    "report_subscriptions",
    "rules",
    "rule_changes",
    "rule_desc_sections",
    "rule_impact_changes",
    "rule_tags",
    "rules_default_impacts",
    "rules_parameters",
    "rules_profiles",
    "rule_repositories",
    "sca_analyses",
    "sca_available_fixes",
    "sca_container_analyses",
    "sca_dependencies",
    "sca_encountered_licenses",
    "sca_ir_cve_locations",
    "sca_issue_dimensions",
    "sca_issues",
    "sca_issues_releases",
    "sca_issue_rels_changes",
    "sca_lic_prof_categories",
    "sca_lic_prof_customs",
    "sca_lic_prof_projects",
    "sca_license_profiles",
    "sca_releases",
    "sca_ttr_history",
    "sca_vulnerability_issues",
    "scanner_analysis_cache",
    "schema_migrations",
    "scim_groups",
    "scim_users",
    "scm_accounts",
    "security_alert_instances",
    "security_alert_sca_risks",
    "security_alerts",
    "session_tokens",
    "slack_subscriptions",
    "slack_workspaces",
    "snapshots",
    "telemetry_metrics_sent",
    "users",
    "user_ai_tool_usages",
    "user_bindings",
    "user_bindings_slack",
    "user_dismissed_messages",
    "user_roles",
    "user_tokens",
    "vortex_cag_events",
    "vortex_sqaa_events",
    "webhooks",
    "webhook_deliveries",
    "xsrf_tokens");

  private SonarQubeSchema() {
    // prevents instantiation
  }
}
