CREATE TABLE "SCM_ACCOUNTS"(
    "USER_UUID" CHARACTER VARYING(255) NOT NULL,
    "SCM_ACCOUNT" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "SCM_ACCOUNTS" ADD CONSTRAINT "PK_SCM_ACCOUNTS" PRIMARY KEY("USER_UUID", "SCM_ACCOUNT");
