CREATE TABLE "USER_ROLES"(
    "ID" INTEGER NOT NULL AUTO_INCREMENT (1,1),
    "ORGANIZATION_UUID" VARCHAR(40) NOT NULL,
    "USER_ID" INTEGER,
    "RESOURCE_ID" INTEGER,
    "ROLE" VARCHAR(64) NOT NULL
);
ALTER TABLE "USER_ROLES" ADD CONSTRAINT "PK_USER_ROLES" PRIMARY KEY("ID");
CREATE INDEX "USER_ROLES_RESOURCE" ON "USER_ROLES"("RESOURCE_ID");
CREATE INDEX "USER_ROLES_USER" ON "USER_ROLES"("USER_ID");
