CREATE TABLE "COMPONENTS"(
                             "UUID" CHARACTER VARYING(50) NOT NULL,
                             "KEE" CHARACTER VARYING(1000),
                             "DEPRECATED_KEE" CHARACTER VARYING(400),
                             "NAME" CHARACTER VARYING(2000),
                             "LONG_NAME" CHARACTER VARYING(2000),
                             "DESCRIPTION" CHARACTER VARYING(2000),
                             "ENABLED" BOOLEAN DEFAULT TRUE NOT NULL,
                             "SCOPE" CHARACTER VARYING(3),
                             "QUALIFIER" CHARACTER VARYING(10),
                             "PRIVATE" BOOLEAN NOT NULL,
                             "LANGUAGE" CHARACTER VARYING(20),
                             "COPY_COMPONENT_UUID" CHARACTER VARYING(50),
                             "PATH" CHARACTER VARYING(2000),
                             "UUID_PATH" CHARACTER VARYING(1500) NOT NULL,
                             "BRANCH_UUID" CHARACTER VARYING(50) NOT NULL,
                             "MAIN_BRANCH_PROJECT_UUID" CHARACTER VARYING(50),
                             "B_CHANGED" BOOLEAN,
                             "B_NAME" CHARACTER VARYING(500),
                             "B_LONG_NAME" CHARACTER VARYING(500),
                             "B_DESCRIPTION" CHARACTER VARYING(2000),
                             "B_ENABLED" BOOLEAN,
                             "B_QUALIFIER" CHARACTER VARYING(10),
                             "B_LANGUAGE" CHARACTER VARYING(20),
                             "B_COPY_COMPONENT_UUID" CHARACTER VARYING(50),
                             "B_PATH" CHARACTER VARYING(2000),
                             "B_UUID_PATH" CHARACTER VARYING(1500),
                             "CREATED_AT" TIMESTAMP
);
CREATE INDEX "PROJECTS_QUALIFIER" ON "COMPONENTS"("QUALIFIER" NULLS FIRST);
CREATE INDEX "IDX_MAIN_BRANCH_PRJ_UUID" ON "COMPONENTS"("MAIN_BRANCH_PROJECT_UUID" NULLS FIRST);
CREATE UNIQUE INDEX "COMPONENTS_UUID" ON "COMPONENTS"("UUID" NULLS FIRST);
CREATE INDEX "COMPONENTS_BRANCH_UUID" ON "COMPONENTS"("BRANCH_UUID" NULLS FIRST);
CREATE UNIQUE INDEX "COMPONENTS_KEE_BRANCH_UUID" ON "COMPONENTS"("KEE" NULLS FIRST, "BRANCH_UUID" NULLS FIRST);


CREATE TABLE "PORTFOLIOS"(
                             "UUID" CHARACTER VARYING(40) NOT NULL,
                             "KEE" CHARACTER VARYING(400) NOT NULL,
                             "NAME" CHARACTER VARYING(2000) NOT NULL,
                             "DESCRIPTION" CHARACTER VARYING(2000),
                             "ROOT_UUID" CHARACTER VARYING(40) NOT NULL,
                             "PARENT_UUID" CHARACTER VARYING(40),
                             "PRIVATE" BOOLEAN NOT NULL,
                             "SELECTION_MODE" CHARACTER VARYING(50) NOT NULL,
                             "SELECTION_EXPRESSION" CHARACTER VARYING(4000),
                             "CREATED_AT" BIGINT NOT NULL,
                             "UPDATED_AT" BIGINT NOT NULL,
                             "BRANCH_KEY" CHARACTER VARYING(255)
);
ALTER TABLE "PORTFOLIOS" ADD CONSTRAINT "PK_PORTFOLIOS" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "UNIQ_PORTFOLIOS_KEE" ON "PORTFOLIOS"("KEE" NULLS FIRST);

CREATE TABLE "PORTFOLIO_REFERENCES"(
                                       "UUID" CHARACTER VARYING(40) NOT NULL,
                                       "PORTFOLIO_UUID" CHARACTER VARYING(40) NOT NULL,
                                       "REFERENCE_UUID" CHARACTER VARYING(40) NOT NULL,
                                       "CREATED_AT" BIGINT NOT NULL,
                                       "BRANCH_UUID" CHARACTER VARYING(255)
);
ALTER TABLE "PORTFOLIO_REFERENCES" ADD CONSTRAINT "PK_PORTFOLIO_REFERENCES" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "UNIQ_PORTFOLIO_REFERENCES" ON "PORTFOLIO_REFERENCES"("PORTFOLIO_UUID" NULLS FIRST, "REFERENCE_UUID" NULLS FIRST, "BRANCH_UUID" NULLS FIRST);

CREATE TABLE "PORTFOLIO_PROJECTS"(
                                     "UUID" CHARACTER VARYING(40) NOT NULL,
                                     "PORTFOLIO_UUID" CHARACTER VARYING(40) NOT NULL,
                                     "PROJECT_UUID" CHARACTER VARYING(40) NOT NULL,
                                     "CREATED_AT" BIGINT NOT NULL
);
ALTER TABLE "PORTFOLIO_PROJECTS" ADD CONSTRAINT "PK_PORTFOLIO_PROJECTS" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "UNIQ_PORTFOLIO_PROJECTS" ON "PORTFOLIO_PROJECTS"("PORTFOLIO_UUID" NULLS FIRST, "PROJECT_UUID" NULLS FIRST);
