CREATE TABLE "ES_QUEUE" (
  "UUID" VARCHAR(40) NOT NULL,
  "DOC_TYPE" VARCHAR(40) NOT NULL,
  "DOC_ID" VARCHAR(4000) NOT NULL,
  "DOC_ID_TYPE" VARCHAR(20),
  "DOC_ROUTING" VARCHAR(4000),
  "CREATED_AT" BIGINT NOT NULL,

  CONSTRAINT "PK_ES_QUEUE" PRIMARY KEY ("UUID")
);
CREATE INDEX "ES_QUEUE_CREATED_AT" ON "ES_QUEUE" ("CREATED_AT");
