CREATE TABLE "SCIM_GROUPS"(
    "SCIM_UUID" CHARACTER VARYING(40) NOT NULL,
    "GROUP_UUID" CHARACTER VARYING(40) NOT NULL
);
ALTER TABLE "SCIM_GROUPS" ADD CONSTRAINT "PK_SCIM_GROUPS" PRIMARY KEY("SCIM_UUID");
