CREATE TABLE "PERM_TEMPLATES_USERS"(
    "ID" INTEGER NOT NULL AUTO_INCREMENT (1,1),
    "UUID" VARCHAR(40) NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "TEMPLATE_ID" INTEGER NOT NULL,
    "PERMISSION_REFERENCE" VARCHAR(64) NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);
