// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: batch_input.proto

package org.sonar.batch.protocol.input;

public final class BatchInput {
  private BatchInput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerIssueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerIssue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional string module_key = 2;</code>
     */
    boolean hasModuleKey();
    /**
     * <code>optional string module_key = 2;</code>
     */
    java.lang.String getModuleKey();
    /**
     * <code>optional string module_key = 2;</code>
     */
    com.google.protobuf.ByteString
        getModuleKeyBytes();

    /**
     * <code>optional string path = 3;</code>
     */
    boolean hasPath();
    /**
     * <code>optional string path = 3;</code>
     */
    java.lang.String getPath();
    /**
     * <code>optional string path = 3;</code>
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>optional string rule_repository = 4;</code>
     */
    boolean hasRuleRepository();
    /**
     * <code>optional string rule_repository = 4;</code>
     */
    java.lang.String getRuleRepository();
    /**
     * <code>optional string rule_repository = 4;</code>
     */
    com.google.protobuf.ByteString
        getRuleRepositoryBytes();

    /**
     * <code>optional string rule_key = 5;</code>
     */
    boolean hasRuleKey();
    /**
     * <code>optional string rule_key = 5;</code>
     */
    java.lang.String getRuleKey();
    /**
     * <code>optional string rule_key = 5;</code>
     */
    com.google.protobuf.ByteString
        getRuleKeyBytes();

    /**
     * <code>optional int32 line = 6;</code>
     */
    boolean hasLine();
    /**
     * <code>optional int32 line = 6;</code>
     */
    int getLine();

    /**
     * <code>optional string msg = 7;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 7;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 7;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .Severity severity = 8;</code>
     */
    boolean hasSeverity();
    /**
     * <code>optional .Severity severity = 8;</code>
     */
    org.sonar.batch.protocol.Constants.Severity getSeverity();

    /**
     * <code>optional bool manual_severity = 9;</code>
     */
    boolean hasManualSeverity();
    /**
     * <code>optional bool manual_severity = 9;</code>
     */
    boolean getManualSeverity();

    /**
     * <code>optional string resolution = 10;</code>
     */
    boolean hasResolution();
    /**
     * <code>optional string resolution = 10;</code>
     */
    java.lang.String getResolution();
    /**
     * <code>optional string resolution = 10;</code>
     */
    com.google.protobuf.ByteString
        getResolutionBytes();

    /**
     * <code>optional string status = 11;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional string status = 11;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>optional string status = 11;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>optional string checksum = 12;</code>
     */
    boolean hasChecksum();
    /**
     * <code>optional string checksum = 12;</code>
     */
    java.lang.String getChecksum();
    /**
     * <code>optional string checksum = 12;</code>
     */
    com.google.protobuf.ByteString
        getChecksumBytes();

    /**
     * <code>optional string assignee_login = 13;</code>
     */
    boolean hasAssigneeLogin();
    /**
     * <code>optional string assignee_login = 13;</code>
     */
    java.lang.String getAssigneeLogin();
    /**
     * <code>optional string assignee_login = 13;</code>
     */
    com.google.protobuf.ByteString
        getAssigneeLoginBytes();

    /**
     * <code>optional int64 creation_date = 14;</code>
     */
    boolean hasCreationDate();
    /**
     * <code>optional int64 creation_date = 14;</code>
     */
    long getCreationDate();
  }
  /**
   * Protobuf type {@code ServerIssue}
   */
  public static final class ServerIssue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ServerIssue)
      ServerIssueOrBuilder {
    // Use ServerIssue.newBuilder() to construct.
    private ServerIssue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerIssue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerIssue defaultInstance;
    public static ServerIssue getDefaultInstance() {
      return defaultInstance;
    }

    public ServerIssue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerIssue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              moduleKey_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              path_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              ruleRepository_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              ruleKey_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              line_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              msg_ = bs;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              org.sonar.batch.protocol.Constants.Severity value = org.sonar.batch.protocol.Constants.Severity.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                severity_ = value;
              }
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              manualSeverity_ = input.readBool();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              resolution_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              status_ = bs;
              break;
            }
            case 98: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000800;
              checksum_ = bs;
              break;
            }
            case 106: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00001000;
              assigneeLogin_ = bs;
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              creationDate_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sonar.batch.protocol.input.BatchInput.internal_static_ServerIssue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sonar.batch.protocol.input.BatchInput.internal_static_ServerIssue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sonar.batch.protocol.input.BatchInput.ServerIssue.class, org.sonar.batch.protocol.input.BatchInput.ServerIssue.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerIssue> PARSER =
        new com.google.protobuf.AbstractParser<ServerIssue>() {
      public ServerIssue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerIssue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerIssue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULE_KEY_FIELD_NUMBER = 2;
    private java.lang.Object moduleKey_;
    /**
     * <code>optional string module_key = 2;</code>
     */
    public boolean hasModuleKey() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string module_key = 2;</code>
     */
    public java.lang.String getModuleKey() {
      java.lang.Object ref = moduleKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          moduleKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string module_key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getModuleKeyBytes() {
      java.lang.Object ref = moduleKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moduleKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 3;
    private java.lang.Object path_;
    /**
     * <code>optional string path = 3;</code>
     */
    public boolean hasPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string path = 3;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          path_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string path = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RULE_REPOSITORY_FIELD_NUMBER = 4;
    private java.lang.Object ruleRepository_;
    /**
     * <code>optional string rule_repository = 4;</code>
     */
    public boolean hasRuleRepository() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string rule_repository = 4;</code>
     */
    public java.lang.String getRuleRepository() {
      java.lang.Object ref = ruleRepository_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ruleRepository_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rule_repository = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRuleRepositoryBytes() {
      java.lang.Object ref = ruleRepository_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleRepository_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RULE_KEY_FIELD_NUMBER = 5;
    private java.lang.Object ruleKey_;
    /**
     * <code>optional string rule_key = 5;</code>
     */
    public boolean hasRuleKey() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string rule_key = 5;</code>
     */
    public java.lang.String getRuleKey() {
      java.lang.Object ref = ruleKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ruleKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rule_key = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRuleKeyBytes() {
      java.lang.Object ref = ruleKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINE_FIELD_NUMBER = 6;
    private int line_;
    /**
     * <code>optional int32 line = 6;</code>
     */
    public boolean hasLine() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 line = 6;</code>
     */
    public int getLine() {
      return line_;
    }

    public static final int MSG_FIELD_NUMBER = 7;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 7;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string msg = 7;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEVERITY_FIELD_NUMBER = 8;
    private org.sonar.batch.protocol.Constants.Severity severity_;
    /**
     * <code>optional .Severity severity = 8;</code>
     */
    public boolean hasSeverity() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .Severity severity = 8;</code>
     */
    public org.sonar.batch.protocol.Constants.Severity getSeverity() {
      return severity_;
    }

    public static final int MANUAL_SEVERITY_FIELD_NUMBER = 9;
    private boolean manualSeverity_;
    /**
     * <code>optional bool manual_severity = 9;</code>
     */
    public boolean hasManualSeverity() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool manual_severity = 9;</code>
     */
    public boolean getManualSeverity() {
      return manualSeverity_;
    }

    public static final int RESOLUTION_FIELD_NUMBER = 10;
    private java.lang.Object resolution_;
    /**
     * <code>optional string resolution = 10;</code>
     */
    public boolean hasResolution() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string resolution = 10;</code>
     */
    public java.lang.String getResolution() {
      java.lang.Object ref = resolution_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resolution_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resolution = 10;</code>
     */
    public com.google.protobuf.ByteString
        getResolutionBytes() {
      java.lang.Object ref = resolution_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resolution_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 11;
    private java.lang.Object status_;
    /**
     * <code>optional string status = 11;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string status = 11;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string status = 11;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKSUM_FIELD_NUMBER = 12;
    private java.lang.Object checksum_;
    /**
     * <code>optional string checksum = 12;</code>
     */
    public boolean hasChecksum() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional string checksum = 12;</code>
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          checksum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string checksum = 12;</code>
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSIGNEE_LOGIN_FIELD_NUMBER = 13;
    private java.lang.Object assigneeLogin_;
    /**
     * <code>optional string assignee_login = 13;</code>
     */
    public boolean hasAssigneeLogin() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional string assignee_login = 13;</code>
     */
    public java.lang.String getAssigneeLogin() {
      java.lang.Object ref = assigneeLogin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          assigneeLogin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string assignee_login = 13;</code>
     */
    public com.google.protobuf.ByteString
        getAssigneeLoginBytes() {
      java.lang.Object ref = assigneeLogin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assigneeLogin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATION_DATE_FIELD_NUMBER = 14;
    private long creationDate_;
    /**
     * <code>optional int64 creation_date = 14;</code>
     */
    public boolean hasCreationDate() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int64 creation_date = 14;</code>
     */
    public long getCreationDate() {
      return creationDate_;
    }

    private void initFields() {
      key_ = "";
      moduleKey_ = "";
      path_ = "";
      ruleRepository_ = "";
      ruleKey_ = "";
      line_ = 0;
      msg_ = "";
      severity_ = org.sonar.batch.protocol.Constants.Severity.INFO;
      manualSeverity_ = false;
      resolution_ = "";
      status_ = "";
      checksum_ = "";
      assigneeLogin_ = "";
      creationDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getModuleKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRuleRepositoryBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRuleKeyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, line_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMsgBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, severity_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, manualSeverity_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getResolutionBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getStatusBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getChecksumBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getAssigneeLoginBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, creationDate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getModuleKeyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRuleRepositoryBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRuleKeyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, line_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMsgBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, severity_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, manualSeverity_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getResolutionBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getStatusBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getChecksumBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getAssigneeLoginBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, creationDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonar.batch.protocol.input.BatchInput.ServerIssue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.sonar.batch.protocol.input.BatchInput.ServerIssue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerIssue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerIssue)
        org.sonar.batch.protocol.input.BatchInput.ServerIssueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sonar.batch.protocol.input.BatchInput.internal_static_ServerIssue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sonar.batch.protocol.input.BatchInput.internal_static_ServerIssue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sonar.batch.protocol.input.BatchInput.ServerIssue.class, org.sonar.batch.protocol.input.BatchInput.ServerIssue.Builder.class);
      }

      // Construct using org.sonar.batch.protocol.input.BatchInput.ServerIssue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        moduleKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ruleRepository_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        ruleKey_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        line_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        severity_ = org.sonar.batch.protocol.Constants.Severity.INFO;
        bitField0_ = (bitField0_ & ~0x00000080);
        manualSeverity_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        resolution_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        checksum_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        assigneeLogin_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        creationDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sonar.batch.protocol.input.BatchInput.internal_static_ServerIssue_descriptor;
      }

      public org.sonar.batch.protocol.input.BatchInput.ServerIssue getDefaultInstanceForType() {
        return org.sonar.batch.protocol.input.BatchInput.ServerIssue.getDefaultInstance();
      }

      public org.sonar.batch.protocol.input.BatchInput.ServerIssue build() {
        org.sonar.batch.protocol.input.BatchInput.ServerIssue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sonar.batch.protocol.input.BatchInput.ServerIssue buildPartial() {
        org.sonar.batch.protocol.input.BatchInput.ServerIssue result = new org.sonar.batch.protocol.input.BatchInput.ServerIssue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.moduleKey_ = moduleKey_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ruleRepository_ = ruleRepository_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ruleKey_ = ruleKey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.line_ = line_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.severity_ = severity_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.manualSeverity_ = manualSeverity_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.resolution_ = resolution_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.checksum_ = checksum_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.assigneeLogin_ = assigneeLogin_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.creationDate_ = creationDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sonar.batch.protocol.input.BatchInput.ServerIssue) {
          return mergeFrom((org.sonar.batch.protocol.input.BatchInput.ServerIssue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sonar.batch.protocol.input.BatchInput.ServerIssue other) {
        if (other == org.sonar.batch.protocol.input.BatchInput.ServerIssue.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasModuleKey()) {
          bitField0_ |= 0x00000002;
          moduleKey_ = other.moduleKey_;
          onChanged();
        }
        if (other.hasPath()) {
          bitField0_ |= 0x00000004;
          path_ = other.path_;
          onChanged();
        }
        if (other.hasRuleRepository()) {
          bitField0_ |= 0x00000008;
          ruleRepository_ = other.ruleRepository_;
          onChanged();
        }
        if (other.hasRuleKey()) {
          bitField0_ |= 0x00000010;
          ruleKey_ = other.ruleKey_;
          onChanged();
        }
        if (other.hasLine()) {
          setLine(other.getLine());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000040;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasSeverity()) {
          setSeverity(other.getSeverity());
        }
        if (other.hasManualSeverity()) {
          setManualSeverity(other.getManualSeverity());
        }
        if (other.hasResolution()) {
          bitField0_ |= 0x00000200;
          resolution_ = other.resolution_;
          onChanged();
        }
        if (other.hasStatus()) {
          bitField0_ |= 0x00000400;
          status_ = other.status_;
          onChanged();
        }
        if (other.hasChecksum()) {
          bitField0_ |= 0x00000800;
          checksum_ = other.checksum_;
          onChanged();
        }
        if (other.hasAssigneeLogin()) {
          bitField0_ |= 0x00001000;
          assigneeLogin_ = other.assigneeLogin_;
          onChanged();
        }
        if (other.hasCreationDate()) {
          setCreationDate(other.getCreationDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sonar.batch.protocol.input.BatchInput.ServerIssue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sonar.batch.protocol.input.BatchInput.ServerIssue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object moduleKey_ = "";
      /**
       * <code>optional string module_key = 2;</code>
       */
      public boolean hasModuleKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string module_key = 2;</code>
       */
      public java.lang.String getModuleKey() {
        java.lang.Object ref = moduleKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            moduleKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string module_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getModuleKeyBytes() {
        java.lang.Object ref = moduleKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moduleKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string module_key = 2;</code>
       */
      public Builder setModuleKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        moduleKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string module_key = 2;</code>
       */
      public Builder clearModuleKey() {
        bitField0_ = (bitField0_ & ~0x00000002);
        moduleKey_ = getDefaultInstance().getModuleKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string module_key = 2;</code>
       */
      public Builder setModuleKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        moduleKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <code>optional string path = 3;</code>
       */
      public boolean hasPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string path = 3;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            path_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string path = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string path = 3;</code>
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 3;</code>
       */
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string path = 3;</code>
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ruleRepository_ = "";
      /**
       * <code>optional string rule_repository = 4;</code>
       */
      public boolean hasRuleRepository() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string rule_repository = 4;</code>
       */
      public java.lang.String getRuleRepository() {
        java.lang.Object ref = ruleRepository_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ruleRepository_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rule_repository = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRuleRepositoryBytes() {
        java.lang.Object ref = ruleRepository_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ruleRepository_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rule_repository = 4;</code>
       */
      public Builder setRuleRepository(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ruleRepository_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rule_repository = 4;</code>
       */
      public Builder clearRuleRepository() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ruleRepository_ = getDefaultInstance().getRuleRepository();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rule_repository = 4;</code>
       */
      public Builder setRuleRepositoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ruleRepository_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ruleKey_ = "";
      /**
       * <code>optional string rule_key = 5;</code>
       */
      public boolean hasRuleKey() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string rule_key = 5;</code>
       */
      public java.lang.String getRuleKey() {
        java.lang.Object ref = ruleKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ruleKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rule_key = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRuleKeyBytes() {
        java.lang.Object ref = ruleKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ruleKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rule_key = 5;</code>
       */
      public Builder setRuleKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ruleKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rule_key = 5;</code>
       */
      public Builder clearRuleKey() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ruleKey_ = getDefaultInstance().getRuleKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rule_key = 5;</code>
       */
      public Builder setRuleKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ruleKey_ = value;
        onChanged();
        return this;
      }

      private int line_ ;
      /**
       * <code>optional int32 line = 6;</code>
       */
      public boolean hasLine() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 line = 6;</code>
       */
      public int getLine() {
        return line_;
      }
      /**
       * <code>optional int32 line = 6;</code>
       */
      public Builder setLine(int value) {
        bitField0_ |= 0x00000020;
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 line = 6;</code>
       */
      public Builder clearLine() {
        bitField0_ = (bitField0_ & ~0x00000020);
        line_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 7;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msg_ = value;
        onChanged();
        return this;
      }

      private org.sonar.batch.protocol.Constants.Severity severity_ = org.sonar.batch.protocol.Constants.Severity.INFO;
      /**
       * <code>optional .Severity severity = 8;</code>
       */
      public boolean hasSeverity() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .Severity severity = 8;</code>
       */
      public org.sonar.batch.protocol.Constants.Severity getSeverity() {
        return severity_;
      }
      /**
       * <code>optional .Severity severity = 8;</code>
       */
      public Builder setSeverity(org.sonar.batch.protocol.Constants.Severity value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        severity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Severity severity = 8;</code>
       */
      public Builder clearSeverity() {
        bitField0_ = (bitField0_ & ~0x00000080);
        severity_ = org.sonar.batch.protocol.Constants.Severity.INFO;
        onChanged();
        return this;
      }

      private boolean manualSeverity_ ;
      /**
       * <code>optional bool manual_severity = 9;</code>
       */
      public boolean hasManualSeverity() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bool manual_severity = 9;</code>
       */
      public boolean getManualSeverity() {
        return manualSeverity_;
      }
      /**
       * <code>optional bool manual_severity = 9;</code>
       */
      public Builder setManualSeverity(boolean value) {
        bitField0_ |= 0x00000100;
        manualSeverity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool manual_severity = 9;</code>
       */
      public Builder clearManualSeverity() {
        bitField0_ = (bitField0_ & ~0x00000100);
        manualSeverity_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object resolution_ = "";
      /**
       * <code>optional string resolution = 10;</code>
       */
      public boolean hasResolution() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string resolution = 10;</code>
       */
      public java.lang.String getResolution() {
        java.lang.Object ref = resolution_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resolution_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resolution = 10;</code>
       */
      public com.google.protobuf.ByteString
          getResolutionBytes() {
        java.lang.Object ref = resolution_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resolution_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resolution = 10;</code>
       */
      public Builder setResolution(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        resolution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resolution = 10;</code>
       */
      public Builder clearResolution() {
        bitField0_ = (bitField0_ & ~0x00000200);
        resolution_ = getDefaultInstance().getResolution();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resolution = 10;</code>
       */
      public Builder setResolutionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        resolution_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>optional string status = 11;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string status = 11;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status = 11;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status = 11;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 11;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000400);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 11;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object checksum_ = "";
      /**
       * <code>optional string checksum = 12;</code>
       */
      public boolean hasChecksum() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional string checksum = 12;</code>
       */
      public java.lang.String getChecksum() {
        java.lang.Object ref = checksum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            checksum_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string checksum = 12;</code>
       */
      public com.google.protobuf.ByteString
          getChecksumBytes() {
        java.lang.Object ref = checksum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          checksum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string checksum = 12;</code>
       */
      public Builder setChecksum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        checksum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string checksum = 12;</code>
       */
      public Builder clearChecksum() {
        bitField0_ = (bitField0_ & ~0x00000800);
        checksum_ = getDefaultInstance().getChecksum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string checksum = 12;</code>
       */
      public Builder setChecksumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        checksum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object assigneeLogin_ = "";
      /**
       * <code>optional string assignee_login = 13;</code>
       */
      public boolean hasAssigneeLogin() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional string assignee_login = 13;</code>
       */
      public java.lang.String getAssigneeLogin() {
        java.lang.Object ref = assigneeLogin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            assigneeLogin_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string assignee_login = 13;</code>
       */
      public com.google.protobuf.ByteString
          getAssigneeLoginBytes() {
        java.lang.Object ref = assigneeLogin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          assigneeLogin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string assignee_login = 13;</code>
       */
      public Builder setAssigneeLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        assigneeLogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string assignee_login = 13;</code>
       */
      public Builder clearAssigneeLogin() {
        bitField0_ = (bitField0_ & ~0x00001000);
        assigneeLogin_ = getDefaultInstance().getAssigneeLogin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string assignee_login = 13;</code>
       */
      public Builder setAssigneeLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        assigneeLogin_ = value;
        onChanged();
        return this;
      }

      private long creationDate_ ;
      /**
       * <code>optional int64 creation_date = 14;</code>
       */
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int64 creation_date = 14;</code>
       */
      public long getCreationDate() {
        return creationDate_;
      }
      /**
       * <code>optional int64 creation_date = 14;</code>
       */
      public Builder setCreationDate(long value) {
        bitField0_ |= 0x00002000;
        creationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 creation_date = 14;</code>
       */
      public Builder clearCreationDate() {
        bitField0_ = (bitField0_ & ~0x00002000);
        creationDate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ServerIssue)
    }

    static {
      defaultInstance = new ServerIssue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ServerIssue)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerIssue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServerIssue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021batch_input.proto\032\017constants.proto\"\235\002\n" +
      "\013ServerIssue\022\013\n\003key\030\001 \001(\t\022\022\n\nmodule_key\030" +
      "\002 \001(\t\022\014\n\004path\030\003 \001(\t\022\027\n\017rule_repository\030\004" +
      " \001(\t\022\020\n\010rule_key\030\005 \001(\t\022\014\n\004line\030\006 \001(\005\022\013\n\003" +
      "msg\030\007 \001(\t\022\033\n\010severity\030\010 \001(\0162\t.Severity\022\027" +
      "\n\017manual_severity\030\t \001(\010\022\022\n\nresolution\030\n " +
      "\001(\t\022\016\n\006status\030\013 \001(\t\022\020\n\010checksum\030\014 \001(\t\022\026\n" +
      "\016assignee_login\030\r \001(\t\022\025\n\rcreation_date\030\016" +
      " \001(\003B\"\n\036org.sonar.batch.protocol.inputH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.sonar.batch.protocol.Constants.getDescriptor(),
        }, assigner);
    internal_static_ServerIssue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerIssue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ServerIssue_descriptor,
        new java.lang.String[] { "Key", "ModuleKey", "Path", "RuleRepository", "RuleKey", "Line", "Msg", "Severity", "ManualSeverity", "Resolution", "Status", "Checksum", "AssigneeLogin", "CreationDate", });
    org.sonar.batch.protocol.Constants.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
