CREATE TABLE "COMPONENTS"(
    "UUID" CHARACTER VARYING(50) NOT NULL,
    "KEE" CHARACTER VARYING(1000),
    "DEPRECATED_KEE" CHARACTER VARYING(400),
    "NAME" CHARACTER VARYING(2000),
    "LONG_NAME" CHARACTER VARYING(2000),
    "DESCRIPTION" CHARACTER VARYING(2000),
    "ENABLED" BOOLEAN DEFAULT TRUE NOT NULL,
    "SCOPE" CHARACTER VARYING(3),
    "QUALIFIER" CHARACTER VARYING(10),
    "PRIVATE" BOOLEAN NOT NULL,
    "LANGUAGE" CHARACTER VARYING(20),
    "COPY_COMPONENT_UUID" CHARACTER VARYING(50),
    "PATH" CHARACTER VARYING(2000),
    "UUID_PATH" CHARACTER VARYING(1500) NOT NULL,
    "BRANCH_UUID" CHARACTER VARYING(50) NOT NULL,
    "B_CHANGED" BOOLEAN,
    "B_NAME" CHARACTER VARYING(500),
    "B_LONG_NAME" CHARACTER VARYING(500),
    "B_DESCRIPTION" CHARACTER VARYING(2000),
    "B_ENABLED" BOOLEAN,
    "B_QUALIFIER" CHARACTER VARYING(10),
    "B_LANGUAGE" CHARACTER VARYING(20),
    "B_COPY_COMPONENT_UUID" CHARACTER VARYING(50),
    "B_PATH" CHARACTER VARYING(2000),
    "B_UUID_PATH" CHARACTER VARYING(1500),
    "CREATED_AT" TIMESTAMP
);
CREATE INDEX "PROJECTS_QUALIFIER" ON "COMPONENTS"("QUALIFIER" NULLS FIRST);
CREATE UNIQUE NULLS NOT DISTINCT INDEX "COMPONENTS_UUID" ON "COMPONENTS"("UUID" NULLS FIRST);
CREATE INDEX "COMPONENTS_BRANCH_UUID" ON "COMPONENTS"("BRANCH_UUID" NULLS FIRST);
CREATE UNIQUE NULLS NOT DISTINCT INDEX "COMPONENTS_KEE_BRANCH_UUID" ON "COMPONENTS"("KEE" NULLS FIRST, "BRANCH_UUID" NULLS FIRST);

CREATE TABLE "EVENT_COMPONENT_CHANGES"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "EVENT_UUID" CHARACTER VARYING(40) NOT NULL,
    "EVENT_COMPONENT_UUID" CHARACTER VARYING(50) NOT NULL,
    "EVENT_ANALYSIS_UUID" CHARACTER VARYING(50) NOT NULL,
    "CHANGE_CATEGORY" CHARACTER VARYING(12) NOT NULL,
    "COMPONENT_UUID" CHARACTER VARYING(50) NOT NULL,
    "COMPONENT_KEY" CHARACTER VARYING(400) NOT NULL,
    "COMPONENT_NAME" CHARACTER VARYING(2000) NOT NULL,
    "COMPONENT_BRANCH_KEY" CHARACTER VARYING(255),
    "CREATED_AT" BIGINT NOT NULL
);
ALTER TABLE "EVENT_COMPONENT_CHANGES" ADD CONSTRAINT "PK_EVENT_COMPONENT_CHANGES" PRIMARY KEY("UUID");
CREATE UNIQUE NULLS NOT DISTINCT INDEX "EVENT_COMPONENT_CHANGES_UNIQUE" ON "EVENT_COMPONENT_CHANGES"("EVENT_UUID" NULLS FIRST, "CHANGE_CATEGORY" NULLS FIRST, "COMPONENT_UUID" NULLS FIRST);
CREATE INDEX "EVENT_CPNT_CHANGES_CPNT" ON "EVENT_COMPONENT_CHANGES"("EVENT_COMPONENT_UUID" NULLS FIRST);
CREATE INDEX "EVENT_CPNT_CHANGES_ANALYSIS" ON "EVENT_COMPONENT_CHANGES"("EVENT_ANALYSIS_UUID" NULLS FIRST);

CREATE TABLE "EVENTS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "ANALYSIS_UUID" CHARACTER VARYING(50) NOT NULL,
    "NAME" CHARACTER VARYING(400),
    "CATEGORY" CHARACTER VARYING(50),
    "DESCRIPTION" CHARACTER VARYING(4000),
    "EVENT_DATA" CHARACTER VARYING(4000),
    "EVENT_DATE" BIGINT NOT NULL,
    "CREATED_AT" BIGINT NOT NULL,
    "COMPONENT_UUID" CHARACTER VARYING(50) NOT NULL
);
ALTER TABLE "EVENTS" ADD CONSTRAINT "PK_EVENTS" PRIMARY KEY("UUID");
CREATE INDEX "EVENTS_ANALYSIS" ON "EVENTS"("ANALYSIS_UUID" NULLS FIRST);
CREATE INDEX "EVENTS_COMPONENT_UUID" ON "EVENTS"("COMPONENT_UUID" NULLS FIRST);
