CREATE TABLE "APP_BRANCH_PROJECT_BRANCH"(
    "UUID" VARCHAR(40) NOT NULL,
    "APPLICATION_UUID" VARCHAR(40) NOT NULL,
    "APPLICATION_BRANCH_UUID" VARCHAR(40) NOT NULL,
    "PROJECT_UUID" VARCHAR(40) NOT NULL,
    "PROJECT_BRANCH_UUID" VARCHAR(40) NOT NULL,
    "CREATED_AT" BIGINT NOT NULL
);
