CREATE TABLE "PORTFOLIOS"(
    "UUID" VARCHAR(40) NOT NULL,
    "KEE" VARCHAR(400) NOT NULL,
    "NAME" VARCHAR(2000) NOT NULL,
    "DESCRIPTION" VARCHAR(2000),
    "ROOT_UUID" VARCHAR(40) NOT NULL,
    "PARENT_UUID" VARCHAR(40),
    "PRIVATE" BOOLEAN NOT NULL,
    "SELECTION_MODE" VARCHAR(50) NOT NULL,
    "SELECTION_EXPRESSION" VARCHAR(50),
    "CREATED_AT" BIGINT NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL
);
ALTER TABLE "PORTFOLIOS" ADD CONSTRAINT "PK_PORTFOLIOS" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "UNIQ_PORTFOLIOS_KEE" ON "PORTFOLIOS"("KEE");
