// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone', 'coding-rules/models/coding-rule'], function(Backbone, CodingRule) {
    var CodingRules, _ref;
    return CodingRules = (function(_super) {
      __extends(CodingRules, _super);

      function CodingRules() {
        _ref = CodingRules.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      CodingRules.prototype.model = CodingRule;

      CodingRules.prototype.url = function() {
        return "" + baseUrl + "/api/codingrules/search";
      };

      CodingRules.prototype.parse = function(r) {
        this.paging = r.paging;
        return r.codingrules;
      };

      return CodingRules;

    })(Backbone.Collection);
  });

}).call(this);
