CREATE TABLE "PROJECT_MEASURES"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "VALUE" DOUBLE PRECISION,
    "ANALYSIS_UUID" CHARACTER VARYING(50) NOT NULL,
    "COMPONENT_UUID" CHARACTER VARYING(50) NOT NULL,
    "TEXT_VALUE" CHARACTER VARYING(4000),
    "ALERT_STATUS" CHARACTER VARYING(5),
    "ALERT_TEXT" CHARACTER VARYING(4000),
    "PERSON_ID" INTEGER,
    "VARIATION_VALUE_1" DOUBLE PRECISION,
    "MEASURE_DATA" BINARY LARGE OBJECT,
    "METRIC_UUID" CHARACTER VARYING(40) NOT NULL
);
ALTER TABLE "PROJECT_MEASURES" ADD CONSTRAINT "PK_PROJECT_MEASURES" PRIMARY KEY("UUID");
CREATE INDEX "MEASURES_COMPONENT_UUID" ON "PROJECT_MEASURES"("COMPONENT_UUID" NULLS FIRST);
CREATE INDEX "MEASURES_ANALYSIS_METRIC" ON "PROJECT_MEASURES"("ANALYSIS_UUID" NULLS FIRST, "METRIC_UUID" NULLS FIRST);
CREATE INDEX "PROJECT_MEASURES_METRIC" ON "PROJECT_MEASURES"("METRIC_UUID" NULLS FIRST);
