CREATE TABLE "ALM_APP_INSTALLS" (
  "UUID" VARCHAR(40) NOT NULL,
  "ALM_ID" VARCHAR(40) NOT NULL,
  "OWNER_ID" VARCHAR(4000) NOT NULL,
  "IS_OWNER_USER" BOOLEAN,
  "INSTALL_ID" VARCHAR(4000) NOT NULL,
  "CREATED_AT" BIGINT NOT NULL,
  "UPDATED_AT" BIGINT NOT NULL,

  CONSTRAINT "PK_ALM_APP_INSTALLS" PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX "ALM_APP_INSTALLS_OWNER" ON "ALM_APP_INSTALLS" ("ALM_ID", "OWNER_ID");
CREATE UNIQUE INDEX "ALM_APP_INSTALLS_INSTALL" ON "ALM_APP_INSTALLS" ("ALM_ID", "INSTALL_ID");