CREATE TABLE "EXTERNAL_GROUPS"(
    "GROUP_UUID" CHARACTER VARYING(40) NOT NULL,
    "EXTERNAL_GROUP_ID" CHARACTER VARYING(255) NOT NULL,
    "EXTERNAL_IDENTITY_PROVIDER" CHARACTER VARYING(100) NOT NULL
);
ALTER TABLE "EXTERNAL_GROUPS" ADD CONSTRAINT "PK_EXTERNAL_GROUPS" PRIMARY KEY("GROUP_UUID");
