CREATE TABLE "RULES_METADATA"(
    "RULE_UUID" CHARACTER VARYING(40) NOT NULL,
    "NOTE_DATA" CHARACTER LARGE OBJECT,
    "NOTE_USER_UUID" CHARACTER VARYING(255),
    "NOTE_CREATED_AT" BIGINT,
    "NOTE_UPDATED_AT" BIGINT,
    "REMEDIATION_FUNCTION" CHARACTER VARYING(20),
    "REMEDIATION_GAP_MULT" CHARACTER VARYING(20),
    "REMEDIATION_BASE_EFFORT" CHARACTER VARYING(20),
    "TAGS" CHARACTER VARYING(4000),
    "AD_HOC_NAME" CHARACTER VARYING(200),
    "AD_HOC_DESCRIPTION" CHARACTER LARGE OBJECT,
    "AD_HOC_SEVERITY" CHARACTER VARYING(10),
    "AD_HOC_TYPE" TINYINT,
    "UPDATED_AT" BIGINT NOT NULL
);
ALTER TABLE "RULES_METADATA" ADD CONSTRAINT "PK_RULES_METADATA" PRIMARY KEY("RULE_UUID");
