CREATE TABLE "PORTFOLIOS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "KEE" CHARACTER VARYING(400) NOT NULL,
    "NAME" CHARACTER VARYING(2000) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(2000),
    "ROOT_UUID" CHARACTER VARYING(40) NOT NULL,
    "PARENT_UUID" CHARACTER VARYING(40),
    "PRIVATE" BOOLEAN NOT NULL,
    "SELECTION_MODE" CHARACTER VARYING(50) NOT NULL,
    "SELECTION_EXPRESSION" CHARACTER VARYING(4000),
    "CREATED_AT" BIGINT NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL,
    "BRANCH_KEY" CHARACTER VARYING(255),
    "MEASURES_MIGRATED" BOOLEAN DEFAULT FALSE NOT NULL
);
ALTER TABLE "PORTFOLIOS" ADD CONSTRAINT "PK_PORTFOLIOS" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "UNIQ_PORTFOLIOS_KEE" ON "PORTFOLIOS"("KEE" NULLS FIRST);

CREATE TABLE "METRICS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "NAME" CHARACTER VARYING(64) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "DIRECTION" INTEGER DEFAULT 0 NOT NULL,
    "DOMAIN" CHARACTER VARYING(64),
    "SHORT_NAME" CHARACTER VARYING(64),
    "QUALITATIVE" BOOLEAN DEFAULT FALSE NOT NULL,
    "VAL_TYPE" CHARACTER VARYING(8),
    "ENABLED" BOOLEAN DEFAULT TRUE,
    "WORST_VALUE" DOUBLE PRECISION,
    "BEST_VALUE" DOUBLE PRECISION,
    "OPTIMIZED_BEST_VALUE" BOOLEAN,
    "HIDDEN" BOOLEAN,
    "DELETE_HISTORICAL_DATA" BOOLEAN,
    "DECIMAL_SCALE" INTEGER
);
ALTER TABLE "METRICS" ADD CONSTRAINT "PK_METRICS" PRIMARY KEY("UUID");
CREATE UNIQUE INDEX "METRICS_UNIQUE_NAME" ON "METRICS"("NAME" NULLS FIRST);

CREATE TABLE "LIVE_MEASURES"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "PROJECT_UUID" CHARACTER VARYING(50) NOT NULL,
    "COMPONENT_UUID" CHARACTER VARYING(50) NOT NULL,
    "METRIC_UUID" CHARACTER VARYING(40) NOT NULL,
    "VALUE" DOUBLE PRECISION,
    "TEXT_VALUE" CHARACTER VARYING(4000),
    "MEASURE_DATA" BINARY LARGE OBJECT,
    "UPDATE_MARKER" CHARACTER VARYING(40),
    "CREATED_AT" BIGINT NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL
);
ALTER TABLE "LIVE_MEASURES" ADD CONSTRAINT "PK_LIVE_MEASURES" PRIMARY KEY("UUID");
CREATE INDEX "LIVE_MEASURES_PROJECT" ON "LIVE_MEASURES"("PROJECT_UUID" NULLS FIRST);
CREATE UNIQUE INDEX "LIVE_MEASURES_COMPONENT" ON "LIVE_MEASURES"("COMPONENT_UUID" NULLS FIRST, "METRIC_UUID" NULLS FIRST);

CREATE TABLE "MEASURES"(
    "COMPONENT_UUID" CHARACTER VARYING(40) NOT NULL,
    "BRANCH_UUID" CHARACTER VARYING(40) NOT NULL,
    "JSON_VALUE" CHARACTER LARGE OBJECT NOT NULL,
    "JSON_VALUE_HASH" BIGINT NOT NULL,
    "CREATED_AT" BIGINT NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL
);
ALTER TABLE "MEASURES" ADD CONSTRAINT "PK_MEASURES" PRIMARY KEY("COMPONENT_UUID");
CREATE INDEX "MEASURES_BRANCH_UUID" ON "MEASURES"("BRANCH_UUID" NULLS FIRST);
