CREATE TABLE "CE_QUEUE"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "TASK_TYPE" CHARACTER VARYING(15) NOT NULL,
    "MAIN_COMPONENT_UUID" CHARACTER VARYING(40),
    "COMPONENT_UUID" CHARACTER VARYING(40),
    "STATUS" CHARACTER VARYING(15),
    "SUBMITTER_UUID" CHARACTER VARYING(255),
    "STARTED_AT" BIGINT,
    "WORKER_UUID" CHARACTER VARYING(40),
    "EXECUTION_COUNT" INTEGER NOT NULL,
    "CREATED_AT" BIGINT NOT NULL,
    "UPDATED_AT" BIGINT NOT NULL
);
ALTER TABLE "CE_QUEUE" ADD CONSTRAINT "PK_CE_QUEUE" PRIMARY KEY("UUID");
CREATE INDEX "CE_QUEUE_MAIN_COMPONENT" ON "CE_QUEUE"("MAIN_COMPONENT_UUID" NULLS FIRST);
CREATE INDEX "CE_QUEUE_COMPONENT" ON "CE_QUEUE"("COMPONENT_UUID" NULLS FIRST);
