/*
 * SonarQube
 * Copyright (C) 2009-2018 SonarSource SA
 * mailto:info AT sonarsource DOT com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */
package org.sonar.server.es;

import com.google.common.base.Splitter;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import org.sonar.core.util.stream.MoreCollectors;

import static java.util.Objects.requireNonNull;

public class IndexType {

  private static final String SEPARATOR = "/";
  private static final Splitter SEPARATOR_SPLITTER = Splitter.on(SEPARATOR);

  private final String index;
  private final String type;
  private final String key;

  public IndexType(String index, String type) {
    this.index = requireNonNull(index);
    this.type = requireNonNull(type);
    this.key = index + SEPARATOR + type;
  }

  public String getIndex() {
    return index;
  }

  public String getType() {
    return type;
  }

  public static String[] getIndices(IndexType... indexTypes) {
    return getDetails(IndexType::getIndex, indexTypes);
  }

  public static String[] getTypes(IndexType... indexTypes) {
    return getDetails(IndexType::getType, indexTypes);
  }

  private static String[] getDetails(Function<? super IndexType, ? extends String> function, IndexType... indexTypes) {
    return Arrays.stream(indexTypes).map(function).collect(MoreCollectors.toSet(indexTypes.length)).toArray(new String[0]);
  }

  public String format() {
    return key;
  }

  /**
   * Parse a String generated by {@link #format()}
   */
  public static IndexType parse(String s) {
    List<String> split = SEPARATOR_SPLITTER.splitToList(s);
    if (split.size() != 2) {
      throw new IllegalArgumentException("Unsupported IndexType value: " + s);
    }
    return new IndexType(split.get(0), split.get(1));
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    IndexType indexType = (IndexType) o;
    return key.equals(indexType.key);
  }

  @Override
  public int hashCode() {
    return key.hashCode();
  }

  @Override
  public String toString() {
    return "[" + index + "/" + type + "]";
  }
}
