CREATE TABLE "NOTIFICATIONS"(
    "ID" INTEGER NOT NULL,
    "DATA" BLOB,
    "UUID" VARCHAR(40) NOT NULL,
    "CREATED_AT" BIGINT NOT NULL
);
ALTER TABLE "NOTIFICATIONS" ADD CONSTRAINT "PK_NOTIFICATIONS" PRIMARY KEY("UUID");
