CREATE TABLE "PROJECT_LINKS2" (
  "UUID" VARCHAR(40) NOT NULL PRIMARY KEY,
  "PROJECT_UUID" VARCHAR(50) NOT NULL,
  "LINK_TYPE" VARCHAR(20) NOT NULL,
  "NAME" VARCHAR(128),
  "HREF" VARCHAR(2048) NOT NULL,
  "CREATED_AT" BIGINT NOT NULL,
  "UPDATED_AT" BIGINT NOT NULL
);
