create TABLE "PROJECTS"(
    "UUID" CHARACTER VARYING(40) NOT NULL,
    "KEE" CHARACTER VARYING(400) NOT NULL,
    "QUALIFIER" CHARACTER VARYING(10) NOT NULL,
    "NAME" CHARACTER VARYING(2000),
    "DESCRIPTION" CHARACTER VARYING(2000),
    "PRIVATE" BOOLEAN NOT NULL,
    "TAGS" CHARACTER VARYING(500),
    "CREATED_AT" BIGINT,
    "UPDATED_AT" BIGINT NOT NULL,
    "NCLOC" BIGINT,
    "CREATION_METHOD" CHARACTER VARYING(50)
);
alter table "PROJECTS" add CONSTRAINT "PK_NEW_PROJECTS" PRIMARY KEY("UUID");
create unique NULLS DISTINCT INDEX "UNIQ_PROJECTS_KEE" on "PROJECTS"("KEE" NULLS FIRST);
create index "IDX_QUALIFIER" on "PROJECTS"("QUALIFIER" NULLS FIRST);
