CREATE TABLE "ORGANIZATION_MEMBERS"(
    "ORGANIZATION_UUID" VARCHAR(40) NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "USER_UUID" VARCHAR(40),
);
ALTER TABLE "ORGANIZATION_MEMBERS" ADD CONSTRAINT "PK_ORGANIZATION_MEMBERS" PRIMARY KEY("ORGANIZATION_UUID", "USER_ID");
CREATE INDEX "IX_ORG_MEMBERS_ON_USER_ID" ON "ORGANIZATION_MEMBERS"("USER_ID");

