// flow-typed signature: 23c15c6265e8c0ef292ece4ed48c96f8
// flow-typed version: <<STUB>>/handlebars_v2.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'handlebars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'handlebars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'handlebars/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/ast' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/javascript-compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/parser' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/printer' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/compiler/visitor' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/exception' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/safe-string' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/handlebars/utils' {
  declare module.exports: any;
}

declare module 'handlebars/dist/amd/precompiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/ast' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/base' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/javascript-compiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/parser' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/printer' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/compiler/visitor' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/exception' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/safe-string' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/handlebars/utils' {
  declare module.exports: any;
}

declare module 'handlebars/dist/cjs/precompiler' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.amd' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.amd.min' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.min' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime.amd' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime.amd.min' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/dist/handlebars.runtime.min' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars.runtime' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/base' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/ast' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/base' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/compiler' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/helpers' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/javascript-compiler' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/parser' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/printer' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/compiler/visitor' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/exception' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/runtime' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/safe-string' {
  declare module.exports: any;
}

declare module 'handlebars/lib/handlebars/utils' {
  declare module.exports: any;
}

declare module 'handlebars/lib/index' {
  declare module.exports: any;
}

declare module 'handlebars/lib/precompiler' {
  declare module.exports: any;
}

declare module 'handlebars/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'handlebars/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'handlebars/coverage/lcov-report/prettify'>;
}
declare module 'handlebars/dist/amd/handlebars.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars'>;
}
declare module 'handlebars/dist/amd/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars.runtime'>;
}
declare module 'handlebars/dist/amd/handlebars/base.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/base'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/ast.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/ast'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/base.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/base'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/compiler'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/helpers.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/helpers'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/javascript-compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/javascript-compiler'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/parser.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/parser'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/printer.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/printer'>;
}
declare module 'handlebars/dist/amd/handlebars/compiler/visitor.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/compiler/visitor'>;
}
declare module 'handlebars/dist/amd/handlebars/exception.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/exception'>;
}
declare module 'handlebars/dist/amd/handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/runtime'>;
}
declare module 'handlebars/dist/amd/handlebars/safe-string.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/safe-string'>;
}
declare module 'handlebars/dist/amd/handlebars/utils.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/handlebars/utils'>;
}
declare module 'handlebars/dist/amd/precompiler.js' {
  declare module.exports: $Exports<'handlebars/dist/amd/precompiler'>;
}
declare module 'handlebars/dist/cjs/handlebars.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars'>;
}
declare module 'handlebars/dist/cjs/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars.runtime'>;
}
declare module 'handlebars/dist/cjs/handlebars/base.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/base'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/ast.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/ast'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/base.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/base'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/compiler'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/helpers.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/helpers'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/javascript-compiler'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/parser.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/parser'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/printer.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/printer'>;
}
declare module 'handlebars/dist/cjs/handlebars/compiler/visitor.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/compiler/visitor'>;
}
declare module 'handlebars/dist/cjs/handlebars/exception.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/exception'>;
}
declare module 'handlebars/dist/cjs/handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/runtime'>;
}
declare module 'handlebars/dist/cjs/handlebars/safe-string.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/safe-string'>;
}
declare module 'handlebars/dist/cjs/handlebars/utils.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/handlebars/utils'>;
}
declare module 'handlebars/dist/cjs/precompiler.js' {
  declare module.exports: $Exports<'handlebars/dist/cjs/precompiler'>;
}
declare module 'handlebars/dist/handlebars.amd.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.amd'>;
}
declare module 'handlebars/dist/handlebars.amd.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.amd.min'>;
}
declare module 'handlebars/dist/handlebars.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars'>;
}
declare module 'handlebars/dist/handlebars.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.min'>;
}
declare module 'handlebars/dist/handlebars.runtime.amd.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime.amd'>;
}
declare module 'handlebars/dist/handlebars.runtime.amd.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime.amd.min'>;
}
declare module 'handlebars/dist/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime'>;
}
declare module 'handlebars/dist/handlebars.runtime.min.js' {
  declare module.exports: $Exports<'handlebars/dist/handlebars.runtime.min'>;
}
declare module 'handlebars/lib/handlebars.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars'>;
}
declare module 'handlebars/lib/handlebars.runtime.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars.runtime'>;
}
declare module 'handlebars/lib/handlebars/base.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/base'>;
}
declare module 'handlebars/lib/handlebars/compiler/ast.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/ast'>;
}
declare module 'handlebars/lib/handlebars/compiler/base.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/base'>;
}
declare module 'handlebars/lib/handlebars/compiler/compiler.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/compiler'>;
}
declare module 'handlebars/lib/handlebars/compiler/helpers.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/helpers'>;
}
declare module 'handlebars/lib/handlebars/compiler/javascript-compiler.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/javascript-compiler'>;
}
declare module 'handlebars/lib/handlebars/compiler/parser.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/parser'>;
}
declare module 'handlebars/lib/handlebars/compiler/printer.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/printer'>;
}
declare module 'handlebars/lib/handlebars/compiler/visitor.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/compiler/visitor'>;
}
declare module 'handlebars/lib/handlebars/exception.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/exception'>;
}
declare module 'handlebars/lib/handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/runtime'>;
}
declare module 'handlebars/lib/handlebars/safe-string.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/safe-string'>;
}
declare module 'handlebars/lib/handlebars/utils.js' {
  declare module.exports: $Exports<'handlebars/lib/handlebars/utils'>;
}
declare module 'handlebars/lib/index.js' {
  declare module.exports: $Exports<'handlebars/lib/index'>;
}
declare module 'handlebars/lib/precompiler.js' {
  declare module.exports: $Exports<'handlebars/lib/precompiler'>;
}
declare module 'handlebars/runtime.js' {
  declare module.exports: $Exports<'handlebars/runtime'>;
}
