// flow-typed signature: 8f8db02dd712c6345b7250b10405496a
// flow-typed version: <<STUB>>/react-transform-hmr_v1.0.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-transform-hmr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-transform-hmr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-transform-hmr/lib/index' {
  declare module.exports: any;
}

declare module 'react-transform-hmr/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-transform-hmr/lib/index.js' {
  declare module.exports: $Exports<'react-transform-hmr/lib/index'>;
}
declare module 'react-transform-hmr/src/index.js' {
  declare module.exports: $Exports<'react-transform-hmr/src/index'>;
}
