// flow-typed signature: e8cd022c77103a9fc1cff2adae48e010
// flow-typed version: <<STUB>>/redux-logger_v2.2.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-logger/dist/index' {
  declare module.exports: any;
}

declare module 'redux-logger/dist/index.min' {
  declare module.exports: any;
}

declare module 'redux-logger/lib/index' {
  declare module.exports: any;
}

declare module 'redux-logger/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-logger/dist/index.js' {
  declare module.exports: $Exports<'redux-logger/dist/index'>;
}
declare module 'redux-logger/dist/index.min.js' {
  declare module.exports: $Exports<'redux-logger/dist/index.min'>;
}
declare module 'redux-logger/lib/index.js' {
  declare module.exports: $Exports<'redux-logger/lib/index'>;
}
declare module 'redux-logger/src/index.js' {
  declare module.exports: $Exports<'redux-logger/src/index'>;
}
