// flow-typed signature: cf8f63f0ab212c4370ead7e10333c4e5
// flow-typed version: <<STUB>>/redux-thunk_v1.0.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-thunk/lib/index' {
  declare module.exports: any;
}

declare module 'redux-thunk/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-thunk/lib/index.js' {
  declare module.exports: $Exports<'redux-thunk/lib/index'>;
}
declare module 'redux-thunk/src/index.js' {
  declare module.exports: $Exports<'redux-thunk/src/index'>;
}
