// flow-typed signature: 3a9784075f51835978f71f0002b52a4d
// flow-typed version: <<STUB>>/script-loader_v0.6.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'script-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'script-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'script-loader/addScript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'script-loader/addScript.js' {
  declare module.exports: $Exports<'script-loader/addScript'>;
}
declare module 'script-loader/index' {
  declare module.exports: $Exports<'script-loader'>;
}
declare module 'script-loader/index.js' {
  declare module.exports: $Exports<'script-loader'>;
}
