CREATE TABLE "REPORT_SCHEDULES"
(
    "UUID"                 CHARACTER VARYING(40) NOT NULL,
    "PORTFOLIO_UUID"       CHARACTER VARYING(40),
    "BRANCH_UUID"          CHARACTER VARYING(40),
    "LAST_SEND_TIME_IN_MS" BIGINT                NOT NULL
);
