CREATE TABLE "PROPERTIES"(
	"PROP_KEY" VARCHAR(512) NOT NULL,
	"IS_EMPTY" BOOLEAN NOT NULL,
	"TEXT_VALUE" VARCHAR(4000) NULL,
	"CLOB_VALUE" VARCHAR(4000) NULL,
	"CREATED_AT" INTEGER NOT NULL,
	"COMPONENT_UUID" VARCHAR(40) NULL,
	"UUID" VARCHAR(40) NOT NULL,
	"USER_UUID" VARCHAR(255) NULL
);
