CREATE TABLE "REPORT_SUBSCRIPTIONS"
(
    "UUID"           CHARACTER VARYING(40) NOT NULL,
    "PORTFOLIO_UUID" CHARACTER VARYING(40),
    "BRANCH_UUID"    CHARACTER VARYING(40),
    "USER_UUID"      CHARACTER VARYING(40) NOT NULL
);
