CREATE TABLE "PROPERTIES"
(
    "UUID"        CHARACTER VARYING(40)  NOT NULL,
    "PROP_KEY"    CHARACTER VARYING(512) NOT NULL,
    "IS_EMPTY"    BOOLEAN                NOT NULL,
    "TEXT_VALUE"  CHARACTER VARYING(4000),
    "CLOB_VALUE"  CHARACTER LARGE OBJECT,
    "CREATED_AT"  BIGINT                 NOT NULL,
    "ENTITY_UUID" CHARACTER VARYING(40),
    "USER_UUID"   CHARACTER VARYING(255)
);
ALTER TABLE "PROPERTIES"
    ADD CONSTRAINT "PK_PROPERTIES" PRIMARY KEY ("UUID");
CREATE INDEX "PROPERTIES_KEY" ON "PROPERTIES" ("PROP_KEY" NULLS FIRST);
