CREATE TABLE "USER_PROPERTIES" (
  "UUID" VARCHAR(40) NOT NULL,
  "USER_UUID" VARCHAR(255) NOT NULL,
  "KEE" VARCHAR(100) NOT NULL,
  "TEXT_VALUE" VARCHAR(4000) NOT NULL,
  "CREATED_AT" BIGINT NOT NULL,
  "UPDATED_AT" BIGINT NOT NULL,

  CONSTRAINT "PK_USER_PROPERTIES" PRIMARY KEY ("UUID")
);
CREATE UNIQUE INDEX "USER_PROPERTIES_USER_UUID_KEE" ON "USER_PROPERTIES" ("USER_UUID", "KEE");
